### ISSUE TITLE
prometheus slurm exporter failing

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#187]
Ticket: https://stackhpc.atlassian.net/browse/DEV-1021

service (`prometheus-slurm-exporter`) is constantly failing/restarting. From syslog:

```
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: panic: runtime error: index out of range [4] with length 4
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: goroutine 10 [running]:
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: main.ParseNodeMetrics(0xc000292000, 0xca, 0x600, 0x0)
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: #011/github/home/rpmbuild/BUILD/prometheus-slurm-exporter-0.20/node.go:56 +0x6d6
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: main.NodeGetMetrics(0x0)
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: #011/github/home/rpmbuild/BUILD/prometheus-slurm-exporter-0.20/node.go:40 +0x2a
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: main.(*NodeCollector).Collect(0xc0000ac000, 0xc000188420)
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: #011/github/home/rpmbuild/BUILD/prometheus-slurm-exporter-0.20/node.go:128 +0x37
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: #011/github/home/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x12b
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
May 24 16:09:39 devrebuild-control prometheus-slurm-exporter[113346]: #011/github/home/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe4d
```

**Comment by sjpb** [comment]
Looks like it might be this: https://github.com/vpenso/prometheus-slurm-exporter/issues/80.

Currrent nodename is `devrebuild-control`. Will try shorter `devrev` and see ...

**Comment by sjpb** [comment]
Fixed by above PR
